### ISSUE TITLE
Variable Naming: tap-hold vs. hold-tap

### ISSUE THREAD

**Issue by dariogoetz** [TeXitoi/keyberon#105]
There are inconsistencies with the tap-hold/hold-tap naming, e.g. it is called `TapHoldTracker` but the `Action` is called `HoldTap` and corresponding `HoldTapConfig`.
Then the interval is called `tap_hold_interval` and the tracker is called `tap_hold_tracker`.

I suggest establishing a uniform naming scheme by fixing one of the variants and I would be happy to file a PR for one or the other versions.

**Comment by TeXitoi** [comment]
That's a feature: tap then hold to keep the tap action pressed.

**Comment by dariogoetz** [comment]
Ah, yes. You are right :) My bad.
