### ISSUE TITLE
Implement Custom action

### ISSUE THREAD

**Issue by TssT16** [TeXitoi/keyberon#19]
First of all thanks for the code, I love my DIY keyboard with own keybindings,
my question is now is there a why so simulate the mouse.
So that I have mouse-like with arrow keys.
Or is that in plan?

**Comment by TeXitoi** [comment]
Oh, great! Can I have a photo of tour keyboard to add it to the gallery? Did you also use the 3d printed case?

For the mouse, yes and no.

Basically, I want to provide a library and not a framework, so mouse functionality would be in a different crate.

But I want to provide user defined actions on the keyboard, for non keyboard features as rgb, reset, backlight or mouse.

I didn't find a great interface for it, but the idea would be to add a `Custom(T)` variant to the Action enum, allowing the used to create whatever he want. The difficult part of the api is to provide the custom key events in an ergonomic way.

**Comment by TssT16** [comment]
Shure here is my first prototype built of a wood piece but for the moment I had no diodes.  
So some times I have ghosting I would say ones a week but for the moment it's ok.  
When can I test the first version of the mouse function?
By the way, I had uploaded [my keyboard code](https://github.com/TssT16/keyberon/blob/master/examples/keyberon48.rs) for the 4x12 keyboard. It is also a German layout.

![Back-simple](https://user-images.githubusercontent.com/12481562/81586292-96684180-93b5-11ea-86e8-3808e8962fb0.jpg)
![Front](https://user-images.githubusercontent.com/12481562/81586297-97996e80-93b5-11ea-86e1-c4358854477e.jpg)

**Comment by gilescope** [comment]
Don't those bare wires stand a chance of shorting each other? I thought also some diodes were required ideally but maybe they're optional...

**Comment by TeXitoi** [comment]
That's

**Comment by TeXitoi** [comment]
That's enameled wire, so no risk of shorts.

**Comment by TssT16** [comment]
@gilescope You can get this wires from a old Motor.

**Comment by TeXitoi** [comment]
I personally use https://www.aliexpress.com/item/32960104613.html

**Comment by TeXitoi** [comment]
So, to fix this issue, a Custom action must be possible, with an interface to expose event (action "pressed", action "released") and state (action is currently active).

**Comment by riskable** [comment]
You can use my `SequenceEvent` enum for mouse events.  I'd be happy to start working on `MouseDown` `MouseUp` after my PR gets merged.  Technically it'd probably be something like

```rust
MouseDown {
    button: u8, // e.g. 1 for left click, 2 for middle, 3 for right, etc
}
MouseUp {
    button: u8,
}
MouseMove {
    x: u32,
    y: u32,
}
```

I'm pretty sure the mousewheel is just another button from a USB input event standpoint.  Just speculating at this point...  Might be a difference between something like *moving* the mouse and just having the mouse appear at a specific location.  It's been a while so I forget.

**Comment by TeXitoi** [comment]
No, no direct mouse support in keyberon.

You'd need  #actions and not keycode to support mouse in

**Comment by TeXitoi** [comment]
I think I have a plan for this feature:

Action with a Custom variant, that is a type parameter, default to core::convert::Infallible:

```rust
enum Action<T> {
    // ...
    Custom(T),
}
```

`Layout::tick()` will return a `CustomEvent<T>`

```rust
pub enum CustomEvent<T> {
    NoEvent,
    Press(T),
    Release(T),
}
```

Keyboard report will be extracted with the (already existing) `Layout::keycodes()`.

What do you think?
