### ISSUE TITLE
multiple actions m(&[l(1),k(LShift)])

### ISSUE THREAD

**Issue by gilescope** [TeXitoi/keyberon#23]
Would be cool if we could accept multiple actions

**Comment by TeXitoi** [comment]
What is multiple actions? You mean at the same time? That's possible. You mean successive? There is an issue for that. Another thing?

**Comment by TeXitoi** [comment]
My bad that's multiple keycode that is implemented.

It should be quite easy to do a MultipleActions action.

**Comment by TeXitoi** [comment]
No, don't, I'll do it when I'll have the time.

**Comment by TeXitoi** [comment]
Please tell me if it works as expected!
