### ISSUE TITLE
Custom bootloaders

### ISSUE THREAD

**Issue by Ossss2** [TeXitoi/keyberon#24]
Hi! Great project.
Would custom bootloaders like [stm32f103-keyboard-bootloader](https://github.com/xyzz/stm32f103-keyboard-bootloader) work with Keyberon? If not, which changes would be necessary?

**Comment by TeXitoi** [comment]
https://github.com/TeXitoi/ortho60-keyberon use the arduino bootloader.

Looking at the linked project, it should just work the same.
