### ISSUE TITLE
not-so-latest stable rust breaks things

### ISSUE THREAD

**Issue by gilescope** [TeXitoi/keyberon#55]
I'm getting this with latest rust:
cortex_m_rt::HardFault_ (ef=0x20004e08) at C:\Users\giles\.cargo\registry\src\github.com-1ecc6299db9ec823\cortex-m-rt-0.6.12\src\lib.rs:552 

1.47 is fine. Will binary chop.

**Comment by gilescope** [comment]
1.50 seems bad.
1.48 bad too.
Ah you've fixed this:
https://github.com/TeXitoi/keyberon/commit/2dd1e3d7f3a883804c5dc734bd2a128fdb52eddc

Thank you @TeXitoi  - always got my back!

**Comment by TeXitoi** [comment]
Yup, need master. I'm slowly working on changing the generic matrix support, but I dont find so much time, so v0.2 is waiting...
