### ISSUE TITLE
Emulating typing

### ISSUE THREAD

**Issue by Owez** [TeXitoi/keyberon#64]
Hey there,

I'm currently making a rubberducky clone (https://hak5.org/products/usb-rubber-ducky-deluxe) with some Rust firmware and was wondering how good this crate would be to send arbitrary inputs via usb (similar to native keyboard macros maybe?) or if I should manually implement it instead. Any thoughts?

Thanks :)

**Comment by TeXitoi** [comment]
Maybe https://github.com/TeXitoi/keyberon/pull/30 ?

**Comment by Owez** [comment]
Yep that looks like what I need!
