### ISSUE TITLE
Best method for keeping track of binary repos using keyberon for popular keyboards

### ISSUE THREAD

**Issue by camrbuss** [TeXitoi/keyberon#70]
What is the best way the keyberon "community" can keep track of keyboard firmware that has been put together for common keyboards?

If the designer of the keyboard supports QMK, but someone else writes a keyberon firmware for the board, it would be nice to keep track of this. 

It seems like most popular keyboards running a Arm Cortex-M MCU could be running keyberon, and it would be nice to share this work with newcomers. 

I see the readme starts to do this, but that could get really unwieldy.

**Comment by TeXitoi** [comment]
A simple solution would be a dedicated markdown file with some kind of table listing any keyboard and/or firmware?

**Comment by camrbuss** [comment]
I like that idea. Simple enough and would just take a PR from someone with an addition/modification.

What are you thinking `doc/KEYBOARDS.md`, `KEYBOARDS.md`, `BOARDIMPLEMENTATIONS.md`, `BOARDS.md`, or `IMPLEMENTATIONS.md`?

I am thinking a nice table with the following columns.


| Keyboard         | PCB or Handwired | Firmware License | Feature Status |
|------------------|------------------|------------------|----------------|
| [KeySeeBee](https://github.com/TeXitoi/keyseebee)        | PCB              | MIT              | <ul><li>- [x] Matrix </li><li>- [x] Split</li></ul>    |
| [Arisu](https://github.com/help-14/arisu-handwired)            | Handwired              | MIT              | <ul><li>- [x] Matrix </li></ul>         |
| <name> with link | <>               | <>               |        <ul><li>- [x] Matrix </li><li>- [ ] OLED</li></ul>      |

**Comment by DrewTChrist** [comment]
I'd like to second this. I've recently just developed a firmware with Keyberon for an RP2040 keyboard. The only RP2040 examples I know of belong to @camrbuss and I only happened to find them by searching the around on the internet. I think a list of known Keyberon firmwares would help those wishing to write their own.
