### ISSUE TITLE
Keyberon for a kmonad-style application

### ISSUE THREAD

**Issue by jtroo** [TeXitoi/keyberon#84]
Hello! I'm curious to know if keyberon makes sense to use as a component of a [software keyboard remapper like kmonad](https://github.com/kmonad/kmonad).

Instead of reading a key matrix for inputs and sending output over USB like a keyboard firmware would, kmonad hooks into [OS-specific keyboard hooks](https://github.com/kmonad/kmonad/blob/keycode-refactor/c_src/keyio_win.c), intercepting the raw inputs and sending processed outputs.

Not sure if an issue is the right place for this type of question, but the discussions tab seems to be disabled for this project.

Thanks!

**Comment by TeXitoi** [comment]
Sure it can. It's a library, and you can use the layer object to manage the programmable thing, and you have to feed it and then read the report to send back to the OS.

**Comment by jtroo** [comment]
Thanks, that's good to know!
